# Generated by Django 5.2 on 2025-05-15 19:53

import Room_Booking.supabase_storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room_Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='maxOccupancy',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(storage=Room_Booking.supabase_storage.SupabaseStorage(), upload_to='room_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
